config/routes.rb
Complaint::Application.routes.draw do
  resources :questions

  devise_for :users
  resource :users, :only => [:show, :index]

  get "pages/home"
  root "pages#home"
  get "threads" => "questions#index"
  get "gyaan" => "pages#gyaan"

  

end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :user
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 	has_many :questions
 	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/users_controller.rb
class QuestionsController < ApplicationController
	

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@question = current_user.questions.build if current_user
  end

def threads
	@question = current_user.questions.build if current_user
	end

def gyaan
	@question = current_user.questions.build if current_user
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @questions = Question.all
    @question = current_user.questions.build if current_user
  end

  def show
    
  end

  def new
    @question = current_user.questions.build
    end

  def edit
  
  end

  def create
    @question = current_user.questions.build(question_params)
    if @question.save
        redirect_to @question, notice: 'Question was successfully created.'
      else
        render action: 'new'    
      end
  end

  def update
    if @question.update(question_params)
      redirect_to @question, notice: 'Question was successfully updated.'
      else
      render action: 'edit'    
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_url
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    def correct_user
      @question = current_user.questions.find_by(id: params[:id])
      redirect_to questions_path if @question.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Consumer Tadka", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Gyaan<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Auto</a></li>
            <li><a href="#">Finance</a></li>
            <li><a href="#">Telecom</a></li>
            <li><a href="#">Technology</a></li>
            <li><a href="#">Travel</a></li>
            <li><a href="#">Real Estate</a></li>
            <li class="divider"></li>
            <li><%= link_to "Full Gyaan", gyaan_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Threads<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Auto</a></li>
            <li><a href="#">Finance</a></li>
            <li><a href="#">Telecom</a></li>
            <li><a href="#">Technology</a></li>
            <li><a href="#">Travel</a></li>
            <li><a href="#">Real Estate</a></li>
            <li class="divider"></li>
            <li><%= link_to "Threads Base", threads_path %></li>
          </ul>
        </li>
        <% if user_signed_in? %>
      <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      <li><%= link_to "Account Settings", edit_user_registration_path %></li>
      <% else %>
      <li><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>
      </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- / .container -->
</nav>

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
  <div class="Main-message">
    <h3>Consumer Shield</h3>
  </div>
    <div class="Complaints-Box">
      <form role="form">
        <div class="form-group">
          <label for="exampleInputEmail1"><h4 class="index">Brand Complaints</h4></label>
          <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Which brand is your complaint against?">
          <button type="submit" class="btn btn-primary"><%= link_to "Resolve my complaint", "http://www.akosha.com", :target => "_blank" %> </button>
        </div>
      </form>
    </div>
        <div class="Colour-One">
        </div>
            <div class="Forum">
              <% if user_signed_in? %>
              <%= form_for(@question) do |f| %>
              <% if @question.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
                  <ul>
                  <% @question.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>
            </div>
              <div class="field">
                <%= f.label :description, "Community Support" %><br>
                <%= f.text_area :description, :placeholder=> "Ask a question", :size=>"30*30", :maxlength=> "300" %>
              </div>
              <div class="actions">
                <%= f.submit %>
                </div>
                <% end %>
                <% else %>
              <div class="Community-Support">
                  <h4>Community Support</h4>
                  <ul class="nav nav-tabs" role="tablist">
                  <li class="active"><a href="#tab1" data-toggle="tab">Log In</a></li>
                  <li><a href="#tab2" data-toggle="tab">Sign up</a></li>
                  </ul>
                    <div class="tab-content">
                    <div class="tab-pane active" id="tab1">
                      <%= form_for(:user, :url => session_path(:user)) do |f| %>
                      <%= f.text_field :email %>
                      <%= f.password_field :password %>
                      <%= f.check_box :remember_me %>
                      <%= f.label :remember_me %>
                      <%= f.submit 'Sign in' %>
                      <%= link_to "Forgot your password?", new_password_path(:user) %>
                    <% end %>
                    </div>
                  <div class="tab-pane" id="tab2">
                    <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
                    <%= devise_error_messages! %>

                    <div><%= f.label :email %><br />
                    <%= f.email_field :email %></div>

                    <div><%= f.label :password %><br />
                    <%= f.password_field :password %></div>

                    <div><%= f.label :password_confirmation %><br />
                    <%= f.password_field :password_confirmation %></div>

                    <div><%= f.submit "Sign up" %></div>
                  </div>
                  <% end %>
                  </div>
                  <% end %>
                                
    <div class="Knowledge-Box">
    <div class="Categories">
      <h4>Knowledge Base</h4>
        <button type="submit" class="btn btn-default"><%= link_to "Auto", "#", :target => "_blank" %> </button>
        <button type="submit" class="btn btn-default"><%= link_to "Finance", "#", :target => "_blank" %> </button>
        <button type="submit" class="btn btn-default"><%= link_to "Telecom", "#", :target => "_blank" %> </button>
        <button type="submit" class="btn btn-default"><%= link_to "Technology", "#", :target => "_blank" %> </button>
        <button type="submit" class="btn btn-default"><%= link_to "Travel", "#", :target => "_blank" %> </button>
        <button type="submit" class="btn btn-default"><%= link_to "Real Estate", "#", :target => "_blank" %> </button>
        <button type="submit" class="btn btn-default"><%= link_to "Online Shopping", "#", :target => "_blank" %> </button>
      </div>
  </div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Complaint</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= render 'layouts/sidebar' %>
<div class="container">
	<% flash.each do |name, msg| %>
	  <%= content_tag(:div, msg, class: "alert alert-info") %>
	<% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/pages/home.html.erb
<h1>Hi</h1>

app/views/pages/threads.html.erb
<h1>About Us</h1>
<p>We are working</p>

app/views/questions/_form.html.erb
<%= form_for @question, html: { multipart: true } do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

 <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Description</th>
      <th>User</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= image_tag question.image.url(:medium) %></td>
        <td><%= question.description %></td>
        <td><%= question.user.email %></td>
        <td><%= link_to 'Show', question %></td>
        <% if question.user == current_user %>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'New Question', new_question_path %>
<% end %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<%= image_tag @question.image.url %>

<p>
  <strong>Description:</strong>
  <%= @question.description %>
</p>

<% if @question.user == current_user %>
<%= link_to 'Edit', edit_question_path(@question) %> |
<% end %>
<%= link_to 'Back', questions_path %>

<%= @questions = user.questions %>